### ISSUE TITLE
Airspeed improvements (TODO list)

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#1907]
- [x] Replace CAS/TAS with IAS (IAS is more indicative to the pilot and more useful for i.e. PID scaling since it defines aircraft behavior at given dynamic pressure. In hot air and cold air stall will occur at different TAS, but at same IAS) (#1841)
- [ ] Use IAS for PID scaling on airplanes
- [x] Add IAS to telemetries (#1841)
- [ ] Add IAS to MSP API
- [ ] Add IAS closed loop control to navigation modes
- [ ] Docs update
- [x] Add IAS to OSD (#1968)

**Comment by Tdogb** [comment]
Any plans on adding airspeed to MSP?

**Comment by DzikuVx** [comment]
@Tdogb #2853
