### ISSUE TITLE
Update APIs to match Betaflights's

### ISSUE THREAD

**Issue by fiam** [iNavFlight/inav#2536]
The goal of this issue is updating several APIs across iNAV to bring them in line with Betaflight. This will allow us to share more code between the two projects (like e.g. the RX and telemetry code). I do plan to submit a few PRs to Betaflight in the process to split some parts that need to be different in the two firmwares (e.g. flight mode reporting in the telemetry) into dedicated files, so we can for example share the `smarport.c` file but have the flight mode encoding somewhere else which is called from `smartport.c`.

- [x] Update Battery API (merged in #2902)
- [x] Update serial API to allow callback arguments (merged in #2537)
- [x] Migrate all preprocessor constants for feature toggles to the `USE_` prefix (merged in #2546)
- [x] ~Update VTX control API~ some parts of VTX control were rewritten in INAV to save RAM/flash
- [x] ~Bring in the API for task dispatching (fc_dispatch.{c,h})~ we've decided to not use this for now

**Comment by martinbudden** [comment]
Great stuff.
